### ISSUE TITLE
bug: plan calculate desired can panic

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/dns-operator#325]
Plan calculate desired can panic in certain cases. 

Observed only with Azure at scale (10+ records for the same host)

```
controller-manager-57db8d94d7-6gdr4 manager panic: runtime error: index out of range [4] with length 4 [recovered]
controller-manager-57db8d94d7-6gdr4 manager     panic: runtime error: index out of range [4] with length 4
controller-manager-57db8d94d7-6gdr4 manager 
controller-manager-57db8d94d7-6gdr4 manager goroutine 290 [running]:
controller-manager-57db8d94d7-6gdr4 manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
controller-manager-57db8d94d7-6gdr4 manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:111 +0x1e5
controller-manager-57db8d94d7-6gdr4 manager panic({0x1dab8a0?, 0xc00084eab0?})
controller-manager-57db8d94d7-6gdr4 manager     /usr/local/go/src/runtime/panic.go:770 +0x132
controller-manager-57db8d94d7-6gdr4 manager github.com/kuadrant/dns-operator/internal/external-dns/plan.(*managedRecordSetChanges).calculateDesired(0xc0007af0c8, 0xc0006c7ac0)
controller-manager-57db8d94d7-6gdr4 manager     /workspace/internal/external-dns/plan/plan.go:542 +0x9b3
controller-manager-57db8d94d7-6gdr4 manager github.com/kuadrant/dns-operator/internal/external-dns/plan.(*managedRecordSetChanges).Calculate(0xc0007af0c8)
controller-manager-57db8d94d7-6gdr4 manager     /workspace/internal/external-dns/plan/plan.go:452 +0x28b
controller-manager-57db8d94d7-6gdr4 manager github.com/kuadrant/dns-operator/internal/external-dns/plan.(*Plan).Calculate(0xc000b5ac60)
controller-manager-57db8d94d7-6gdr4 manager     /workspace/internal/external-dns/plan/plan.go:345 +0x8ff
controller-manager-57db8d94d7-6gdr4 manager github.com/kuadrant/dns-operator/internal/controller.(*DNSRecordReconciler).applyChanges(0xc0006dcb48?, {0x257a088, 0xc000544630}, 0xc0006dcb48, 0xc000440690, {0x2580860, 0xc00098ac60}, 0x0)
controller-manager-57db8d94d7-6gdr4 manager     /workspace/internal/controller/dnsrecord_controller.go:675 +0xc5a
controller-manager-57db8d94d7-6gdr4 manager github.com/kuadrant/dns-operator/internal/controller.(*DNSRecordReconciler).publishRecord(0xc0006cbef0, {0x257a088, 0xc000544630}, 0xc0006dcb48, 0xc000440690, {0x2580860, 0xc00098ac60})
controller-manager-57db8d94d7-6gdr4 manager     /workspace/internal/controller/dnsrecord_controller.go:460 +0xcd
controller-manager-57db8d94d7-6gdr4 manager github.com/kuadrant/dns-operator/internal/controller.(*DNSRecordReconciler).Reconcile(0xc0006cbef0, {0x257a088, 0xc000e09ad0}, {{{0xc000ab3ca0?, 0x5?}, {0xc0005cc7c0?, 0xc000d5dd50?}}})
controller-manager-57db8d94d7-6gdr4 manager     /workspace/internal/controller/dnsrecord_controller.go:243 +0x158c
controller-manager-57db8d94d7-6gdr4 manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x257ea48?, {0x257a088?, 0xc000e09ad0?}, {{{0xc000ab3ca0?, 0xb?}, {0xc0005cc7c0?, 0x0?}}})
controller-manager-57db8d94d7-6gdr4 manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:114 +0xb7
controller-manager-57db8d94d7-6gdr4 manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00011ea50, {0x257a0c0, 0xc0006d86e0}, {0x1ce72c0, 0xc0006c64a0})
controller-manager-57db8d94d7-6gdr4 manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:311 +0x3bc
controller-manager-57db8d94d7-6gdr4 manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00011ea50, {0x257a0c0, 0xc0006d86e0})
controller-manager-57db8d94d7-6gdr4 manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:261 +0x1c9
controller-manager-57db8d94d7-6gdr4 manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
controller-manager-57db8d94d7-6gdr4 manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:222 +0x79
controller-manager-57db8d94d7-6gdr4 manager created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 120
controller-manager-57db8d94d7-6gdr4 manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:218 +0x486
```

**Comment by maksymvavilov** [comment]
Resolving in #461 by [this](https://github.com/Kuadrant/dns-operator/pull/461/files#diff-3d0a9b3f94d62d7371fd9bf8f3fb90df1e45b24138ba21b4c228b0e50677f74eR531) change
